trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  displayName: Use Python 3.12
  inputs:
    versionSpec: '3.12'

- script: |
    python --version
    python -m pip install --upgrade pip
  displayName: Setup Python

- script: |
    python -m pip install -r requirements.txt
  displayName: Install Dependencies

- script: |
    python -m py_compile app.py
  displayName: Validate Application